# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Waiwai spellchecker"
waw = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Waiwai, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
waw = "TRANSLATE: A spellchecker for Waiwai, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.waw"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"

[package.speller]
name = "Waiwai"
version = "0.1.0"

[package.grammar]
name = "Waiwai"
version = "0.1.0"

[package.tts-text-proc]
name = "Waiwai"
version = "0.1.0"

[package.hyphenator]
name = "Waiwai"
version = "0.1.0"
