template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "waiw1244"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-waw"
__UND2C__ = "waw"
__UNDEFINED__ = "Waiwai"
__UND__ = "waw"
