template = "https://github.com/giellalt/template-lang-und"
rev_id = 263
template_sha = "1bc24707891f274cd9b2690b032d9864fa1205f5"

[replacements]
__GLOTTOLOG_ID__ = "waiw1244"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-waw"
__UND2C__ = "waw"
__UNDEFINED__ = "Waiwai"
__UND__ = "waw"
