template = "https://github.com/giellalt/template-lang-und"
rev_id = 240
template_sha = "6d8d3d1c387a311925544b3f34dfe8cd2f284ae8"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-waw"
__UND2C__ = "waw"
__UNDEFINED__ = "Waiwai"
__UND__ = "waw"
